### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ptman** [raja/argon2pw#1]
Hi! Would you be able to explain why one should use this instead of https://godoc.org/golang.org/x/crypto/argon2 ?

**Comment by raja** [comment]
Hi Paul,

This abstraction utilizes crypto/argon2 and crypto/rand (for salt generation). It's a convenience package, with strong default parameters, for those that wish to use argon2 key derivation for the purposes of securely persisting salted password hashes to storage and performing password checks in constant time.
